### PR TITLE
Better `float32` error in `save()`

### LINKED ISSUE #810: Better error message when trying to `save()` `float32` TensorMap
Code:
```
dos_tensormap = TensorMap(
    keys=Labels.single(),
    blocks=[block_from_array(torch.load("dos.pt"), sample_names=["system"], property_names=["spline_point"])],
)
save("dos.npz", dos_tensormap)
```

Current error message:
```
  blocks=[block_from_array(torch.load("dos.pt"), sample_names=["system"], property_names=["spline_point"])],
Traceback (most recent call last):
  File "/home/filippo/code/dos/process.py", line 31, in <module>
    save("dos.npz", dos_tensormap)
  File "/home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: error in C++ callback: can not access the data of this torch::Tensor: expected a dtype of float64, got float
Exception raised from data at /project/metatensor-torch/src/array.cpp:65 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7baeef42e446 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2ae44 (0x7bae28e5ee44 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/torch/torch-2.5/lib/libmetatensor_torch.so)
frame #2: <unknown function> + 0x756ff (0x7bae28ea96ff in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/torch/torch-2.5/lib/libmetatensor_torch.so)
frame #3: <unknown function> + 0x5d35b (0x7baea1f7335b in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/lib/libmetatensor.so)
frame #4: <unknown function> + 0x3c0a7 (0x7baea1f520a7 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/lib/libmetatensor.so)
frame #5: <unknown function> + 0x294c6 (0x7baea1f3f4c6 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/lib/libmetatensor.so)
frame #6: <unknown function> + 0x2bc31 (0x7baea1f41c31 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/lib/libmetatensor.so)
frame #7: mts_tensormap_save + 0x20 (0x7baea1f814f0 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/lib/libmetatensor.so)
frame #8: metatensor_torch::TensorMapHolder::save(std::string const&) const + 0x13 (0x7bae28ead8e3 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/torch/torch-2.5/lib/libmetatensor_torch.so)
frame #9: <unknown function> + 0xdd269 (0x7bae28f11269 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/torch/torch-2.5/lib/libmetatensor_torch.so)
frame #10: <unknown function> + 0x103aa5 (0x7bae28f37aa5 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/metatensor/torch/torch-2.5/lib/libmetatensor_torch.so)
frame #11: c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const + 0x238 (0x7baeee108f48 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #12: torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args const&, pybind11::kwargs const&, std::optional<c10::DispatchKey>) + 0xf6 (0x7baeede97876 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #13: torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args const&, pybind11::kwargs const&, bool, std::optional<c10::DispatchKey>) + 0x157 (0x7baeede97be7 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x97fea7 (0x7baeedd7fea7 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #15: <unknown function> + 0x4cc1e3 (0x7baeed8cc1e3 in /home/filippo/code/virtualenvs/base/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #16: python() [0x5820ff]
<omitting python frames>
frame #20: python() [0x5a3698]
frame #24: python() [0x608b52]
frame #25: python() [0x6b4d83]
frame #30: <unknown function> + 0x2a1ca (0x7baeefc2a1ca in /lib/x86_64-linux-gnu/libc.so.6)
frame #31: __libc_start_main + 0x8b (0x7baeefc2a28b in /lib/x86_64-linux-gnu/libc.so.6)
```

### PR DESCRIPTION
**Pull request by frostedoyster**
Closes #810

# Contributor (creator of pull-request) checklist

 - [x] Tests updated (for new features and bugfixes)?
 - [ ] Documentation updated (for new features)?
 - [x] Issue referenced (for PRs that solve an issue)?

# Reviewer checklist

 - [ ] CHANGELOG updated with public API or any other important changes?

----
 📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2395244172.zip)

### CODE REVIEW

**Comment by frostedoyster** [comment]
Not sure what the error message is for the numpy equivalent, so I don't know if that also needs improving

File: metatensor-torch/src/block.cpp [hunk 1]
```diff
@@ -331,6 +331,13 @@ TorchTensorBlock TensorBlockHolder::load_buffer(torch::Tensor buffer) {
 
 
 void TensorBlockHolder::save(const std::string& path) const {
+    // check that dtype is float64
+    if (this->scalar_type() != torch::kFloat64) {
+        C10_THROW_ERROR(ValueError,
+            "cannot save TensorBlock with dtype " + scalar_type_name(this->scalar_type()) +
+            ", only float64 is supported"
+        );
+    }
```
Comment (Luthaf) [inline metatensor-torch/src/block.cpp:340]: should we also give a better error message for the device? I'm fairly sure the data needs to be on CPU.

**Comment by Luthaf** [comment]
CI failure should be fixed after updating the branch with respect to `main`

File: dump_to_disk.py
Comment (Luthaf) [inline dump_to_disk.py:1]: this seems wrong, did you `git add` an extra file?

Comment (frostedoyster) [reply dump_to_disk.py:1]: Yes, my bad
